# --- !Ups
create table "STYLE" (
	"ID" bigint generated by default as identity(start with 1) primary key,
	"NAME" varchar not null,
	"IMAGE_URL" varchar not null
);

insert into STYLE("ID","NAME","IMAGE_URL") values(1, '新中式', 'https://www.baidu.com');

# --- !Downs
drop table "STYLE" if exists;